defmodule ConversationService.Schemas.CallLink do
  @moduledoc """
  Ecto schema for the `call_links` table (Call-link L1). A reusable, WhatsApp-style link whose `id` IS the
  url-safe link code. When someone joins, `CallStore.join_call_link` finds-or-creates a conversation-LESS
  `calls` row (kind="link", conversation_id NULL, link_id=<this id>). No conversation_id here — a link
  belongs to its creator, not a conversation. `require_approval` is stored now; enforcement is L3.
  """

  use Ecto.Schema

  import Ecto.Changeset

  # The PK is the link code itself (a generated url-safe string) — not autogenerated by Ecto.
  @primary_key {:id, :string, autogenerate: false}

  @types ~w(voice video)

  schema "call_links" do
    field(:creator_id, :binary_id)
    field(:type, :string)
    field(:require_approval, :boolean, default: false)
    field(:active, :boolean, default: true)
    field(:created_at, :utc_datetime_usec)
  end

  def create_changeset(attrs) do
    %__MODULE__{}
    |> cast(attrs, [:id, :creator_id, :type, :require_approval, :active, :created_at])
    |> validate_required([:id, :creator_id, :type, :created_at])
    |> validate_inclusion(:type, @types)
    |> unique_constraint(:id, name: "call_links_pkey")
  end
end
