defmodule ConversationService.Schemas.GroupInviteLink do
  @moduledoc """
  Ecto schema for `group_invite_links` (077). The `code` IS the url-safe link code (PK) — a shareable,
  WhatsApp-style link to JOIN a group without an owner add. One ACTIVE link per conversation (a partial
  unique index enforces it); revoke sets `active=false`. `app_id` is denormalised from the conversation so
  a code only resolves within its tenant. Mirrors `call_links` (069).
  """

  use Ecto.Schema

  import Ecto.Changeset

  # The PK is the link code itself (a generated 128-bit url-safe string) — not autogenerated by Ecto.
  @primary_key {:code, :string, autogenerate: false}

  schema "group_invite_links" do
    field(:conversation_id, :binary_id)
    field(:app_id, :binary_id)
    field(:created_by, :binary_id)
    field(:active, :boolean, default: true)
    field(:created_at, :utc_datetime_usec)
  end

  def create_changeset(attrs) do
    %__MODULE__{}
    |> cast(attrs, [:code, :conversation_id, :app_id, :created_by, :active, :created_at])
    |> validate_required([:code, :conversation_id, :app_id, :created_by, :created_at])
    |> unique_constraint(:code, name: "group_invite_links_pkey")
    # The one-active-per-conversation invariant (partial unique index) — a mint racing another mint for the
    # same group surfaces here and the caller retries into the now-existing active link.
    |> unique_constraint(:conversation_id, name: "group_invite_links_active_conversation_idx")
  end
end
